{% set name = "jscatter" %}
{% set version = "1.9.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jscatter-{{ version }}.tar.gz
  sha256: 639306c85f25dbc0539d1c1cfc8eb1fe9c82179472fcb8379f77dc6aee830c07

build:
  script:
    # Remove cython generated files to re-generate them with the version of numpy used to build
    - {{ PYTHON }} -c "import pathlib; [p.with_suffix('.c').unlink() for p in pathlib.Path('.').rglob('*.pyx')]"
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}
  host:
    - python
    - setuptools >=67.0
    - cmake >=3.30.9
    - wheel
    - cython >=3.0
    - numpy >=2
    - pip
  run:
    - llvm-openmp  # [osx]
    - python
    - numpy >=2
    - scipy >=1.15.0
    - matplotlib-base >=3.7
    - pillow >=8.1
    - mdanalysis >=2.4.0
    - netcdf4
    - cython
    - fabio
    - pdb2pqr
    - requests
    - nglview
    - emcee

test:
  imports:
    - jscatter
    # Compiled extensions
    - jscatter.libs.cubature._cubature
    - jscatter.libs.cubature._test_integrands
    - jscatter.libs.surface

about:
  summary: Combines dataArrays with attributes for fitting plotting and analysis including models for Xray and neutron scattering
  license: GPL-3.0-or-later
  license_file: src/jscatter/LICENSE
  home: https://gitlab.com/biehl/jscatter
  doc_url: https://jscatter.readthedocs.io
  dev_url: https://gitlab.com/biehl/jscatter/

extra:
  recipe-maintainers:
    - t20100
